---
title: "Calculate Income-to-Needs at T1"
author: "Lucy King"
output: 
  github_document:
    toc: true
    toc_depth: 6
---


```{r}
##Libraries
library(tidyverse)

##Parameters
#files
income_t1_file <- "~/Desktop/ELS/income_TBM/data/osf/income_t1.csv"
#in SPSS file, first cleaned variable "pplinhome_1_TEXT" and converted to numeric 
tbm_covariates_file <- "~/Desktop/ELS/income_TBM/data/osf/tbm_cov_income.csv"
```

##calculate income-to-needs
```{r}
#income reported in bins, used median for income to needs as in Yu et al. (2017) developmental science
inr <-
  read_csv(income_t1_file) %>% 
  select(
    ELS_ID,
    household_income = Household_Income,
    ppl_in_home = pplinhome_1_TEXT
  ) %>% 
  filter(
    !is.na(household_income)
    ) %>% 
  mutate(
    household_income = as.character(household_income),
    household_income_numeric = as.numeric(
      recode(
        household_income,
        "1" = "5000",
        "2" = "7500",
        "3" = "12500",
        "4" = "20000",
        "5" = "30000",
        "6" = "42500",
        "7" = "62500",
        "8" = "87500",
        "9" = "125000",
        "10" = "150000"
      )
    ),
#santa clara country low-income limit : 80% of median income (ratios <= 1 are therefore "low income")
#https://www.huduser.gov/portal/datasets/il/il2017/2017summary.odn
    SC_lowincome_limit = as.numeric(
      recode(
        ppl_in_home,
        "1" = "59350",
        "2" = "67800",
        "3" = "76300", 
        "4" = "84750",
        "5" = "91500",
        "6" = "98350",
        "7" = "105100",
        "8" = "111900",
        .default = "111900"
      )
    ),
    income_needs = household_income_numeric / SC_lowincome_limit
  )
```


