---
title: "Calculate Income-to-Needs at T1"
author: "Lucy King"
date: "2018-06-14"
output: html_document
---


```{r}
##Libraries
library(tidyverse)

##Parameters
#files
demo_full_file <- "~/Desktop/ELS/income_TBM/data/120616_ELS_T1S1_Demographics Golden Standard.sav"
#in SPSS file, first cleaned variable "pplinhome_1_TEXT" and converted to numeric 
covariates_file <- "~/Desktop/ELS/income_TBM/data/tbm_cov_income.csv"
```

```{r}
#income reported in bins, used median for income to needs as in Yu et al. (2017) developmental science
inr <-
  haven::read_spss(demo_full_file, user_na = 999) %>% 
  select(
    ELS_ID,
    household_income = Household_Income,
    ppl_in_home = pplinhome_1_TEXT
  ) %>% 
  filter(
    !is.na(household_income), 
    household_income != 999,
    household_income != "11"#some are coded in SPSS as 11, which indicates "don't know"
    ) %>% 
  mutate(
    household_income = as.character(household_income),
    household_income_numeric = as.numeric(
      recode(
        household_income,
        "1" = "5000",
        "2" = "7500",
        "3" = "12500",
        "4" = "20000",
        "5" = "30000",
        "6" = "42500",
        "7" = "62500",
        "8" = "87500",
        "9" = "125000",
        "10" = "150000"
      )
    ),
#santa clara country income : 80% of median income (ratios <= 1 are therefore "low income")
#https://www.huduser.gov/portal/datasets/il/il2017/2017summary.odn
    SC_lowincome_limit = as.numeric(
      recode(
        ppl_in_home,
        "1" = "59350",
        "2" = "67800",
        "3" = "76300", 
        "4" = "84750",
        "5" = "91500",
        "6" = "98350",
        "7" = "105100",
        "8" = "111900",
        .default = "111900"
      )
    ),
    income_needs = household_income_numeric / SC_lowincome_limit
  )
    
ggplot(inr, aes(x = income_needs)) + 
  geom_histogram(bins = 30, position = "dodge", fill = "gray", color = "black") +
  theme_bw() 

```


###Compare those included in sample to those not
```{r}
inr <- 
  inr %>% 
  mutate(
    ELS_ID = as.integer(ELS_ID)
    ) %>%
  left_join(
    read_csv(covariates_file) %>% 
      select(
        ELS_ID,
        included = ICV
      ) %>% 
      mutate(ELS_ID = as.integer(ELS_ID)),
    by = "ELS_ID"
  ) %>% 
  mutate(
    included = if_else(
      !is.na(included), 
      "included", "not"
    )
  )

t.test(inr$income_needs ~ inr$included)
```
```

