---
title: "Data for Table 1"
output: 
  github_document:
    toc: true
    toc_depth: 6
---

```{r}
#Libraries
library(tidyverse)
library(knitr)
library(haven)
library(readxl)

#Parameters
demo_t1_file <- "~/Desktop/ELS/income_TBM/data/final_data/demographics_golden_standard.T1.sav"
demo_t2_file <- "~/Desktop/ELS/income_TBM/data/final_data/demographics_golden_standard.T2.sav"
inr_threat_file <- "~/Desktop/ELS/income_TBM/data/final_data/income_threat.csv"
included_file <- "~/Desktop/ELS/income_TBM/data/final_data/included_ids.csv"
volumes_file <- "~/Desktop/ELS/income_TBM/data/final_data/inr_volumes_20190218.xlsx"
```

# Read in data 
```{r}
included <-
  read_csv(included_file) %>% 
  rename(
    included_t1 = included 
  )
```

```{r}
demo_t2 <-
  read_sav(demo_t2_file) %>% 
  mutate(
    tanner_pb_t2s1 = if_else(
      is.na(T2S1_Tanner_female_pubhair), 
      T2S1_Tanner_male_pubhair, 
      T2S1_Tanner_female_pubhair
    ),
    tanner_bt_t2s1 = if_else(
      is.na(T2S1_Tanner_female_breasts),
      T2S1_Tanner_male_testes,
      T2S1_Tanner_female_breasts
    ),
    tanner_pb_t2s2 = if_else(
      is.na(T2S2_Tanner_female_pubhair), 
      T2S2_Tanner_male_pubhair, 
      T2S2_Tanner_female_pubhair
    ),
    tanner_bt_t2s2 = if_else(
      is.na(T2S2_Tanner_female_breasts),
      T2S2_Tanner_male_testes,
      T2S2_Tanner_female_breasts
    )
  ) %>% 
  group_by(ELS_ID) %>% 
  mutate(
    tanner_av_t2s1 = mean(
      c(tanner_pb_t2s1, tanner_bt_t2s1),
      na.rm = TRUE
    ),
    tanner_av_t2s2 = mean(
      c(tanner_pb_t2s2, tanner_bt_t2s2),
      na.rm = TRUE
    )
  )

```


```{r}
demo <-
  read_sav(demo_t1_file) %>% 
  select(
    ELS_ID,
    income = T1_Parent_Income,
    race_pr = T1_KSADS_Child_Race_by_P,
    T1_Tanner_female_pubhair:T1_Tanner_male_testes,
    T1_Child_Sex
  ) %>% 
  mutate(
    sex = if_else(
      T1_Child_Sex == 1,
      "male", "female" 
    )
  ) %>% 
  left_join(
    read_csv(inr_threat_file),
    by = "ELS_ID"
  ) %>% 
  left_join(
    read_xlsx(volumes_file, sheet = "CSX Volumes") %>% 
      select(
        ELS_ID = Subject, 
        T1_ICV:T1_Age
      ),
    by = "ELS_ID"
  ) %>% 
  left_join(
    read_xlsx(volumes_file, sheet = "Long Volumes") %>% 
      select(
        ELS_ID = Subject,
        interval = Interval
      )
  ) %>% 
  left_join(
    included,
    by = "ELS_ID"
  ) %>% 
  mutate(
    tanner_pb = if_else(
      is.na(T1_Tanner_female_pubhair), 
      T1_Tanner_male_pubhair, 
      T1_Tanner_female_pubhair
    ),
    tanner_bt = if_else(
      is.na(T1_Tanner_female_breasts),
      T1_Tanner_male_testes,
      T1_Tanner_female_breasts
    ),
    included_t1 = as.factor(
      if_else(
        !is.na(included_t1),
        1, 0
      )
    ),
    included_t2 = as.factor(
      if_else(
        !is.na(interval),
        1, 0
      )
    )
  ) %>% 
  group_by(ELS_ID) %>% 
  mutate(
    tanner_av = mean(
      c(tanner_pb, tanner_bt),
      na.rm = TRUE
    ),
    T2_Age = T1_Age + interval
  ) %>% 
  left_join(
    demo_t2 %>% 
      select(
        tanner_av_t2s1,
        tanner_av_t2s2
      )
    ) %>% 
  ungroup() %>% 
  distinct(ELS_ID, .keep_all = TRUE)
```



# Missing data analyses
```{r}
t.test(income_needs ~ included_t1, data = demo)
chisq.test(demo$sex, demo$included_t1)
chisq.test(demo$sex, demo$included_t2)

demo <-
  demo %>% 
  filter(included_t1 == 1)
```

```{r}
demo %>% 
  count(sex) %>% 
  mutate(
    per = n / sum(n)
  )
```

```{r}
demo %>% 
  count(income_needs < 1) %>% 
  mutate(
    per = n / sum(n)
  )
```

```{r}
demo %>%
  count(tanner_av <= 3) %>% 
  mutate(
    per = n / sum(n)
  )
```

```{r}
demo %>% 
  summarise_at(
    vars(interval, sumsev_type_THRT, income_needs, T1_Age, T2_Age, tanner_av),
    list(~mean, ~sd, ~min, ~max), na.rm = TRUE
  )

demo %>% 
  group_by(sex) %>% 
  summarise_at(
    vars(interval, sumsev_type_THRT, income_needs, T1_Age, T2_Age, tanner_av, tanner_av_t2s1),
    list(~mean, ~sd, ~min, ~max), na.rm = TRUE
  )
```

```{r}
cor.test(demo$sumsev_type_THRT, demo$income_needs)
```

# Create table
```{r}
descriptives <- 
  demo %>% 
  group_by(sex) %>% 
  summarise_at(
    vars(
      T1_Age, 
      tanner_av,
      income_needs,
      sumsev_type_THRT,
      interval
    ),
    list(~mean),
    na.rm = TRUE
  ) %>% 
  gather(variable, Mean, T1_Age:interval) %>% 
  left_join(
    demo %>% 
      filter(included_t1 == 1, !is.na(sex)) %>% 
      group_by(sex) %>% 
      summarise_at(
        vars(
          T1_Age, 
          tanner_av,
          income_needs,
          sumsev_type_THRT,
          interval
        ),
        list(~sd),
        na.rm = TRUE
      ) %>% 
      gather(variable, SD, T1_Age:interval),
    by = c("variable", "sex")
  ) %>% 
  mutate_at(
    vars(starts_with("Mean"), starts_with("SD")),
    list(~round), digits = 2
  ) %>% 
  unite("Mean_SD", Mean, SD) %>% 
  mutate_at(
    vars(Mean_SD),
    list(
      ~str_replace(
        .,
        "_", " ("
      )
    )
  ) %>% 
  mutate_at(
    vars(Mean_SD),
    list(
      ~paste0(. , ")")
    )
  ) %>% 
  spread(sex, Mean_SD) %>% 
  rename(
    Boys = male,
    Girls = female
  ) 
```

```{r}
race_ethn_descriptives <- 
  demo %>% 
  filter(included_t1 == 1, !is.na(sex)) %>% 
  group_by(sex) %>% 
  count(
    race_pr
  ) %>% 
  mutate(
    race_pr = case_when(
      race_pr == 1 ~ "Caucasian",
      race_pr == 2 ~ "African American",
      race_pr == 3 ~ "Hispanic",
      race_pr == 4 ~ "Asian",
      race_pr == 5 ~ "Biracial",
      race_pr == 6 ~ "Other",
      TRUE ~ "Not reported"
    )
  ) %>% 
  rename(variable = race_pr) %>% 
  arrange(desc(n)) %>% 
  ungroup() %>% 
  select(
    variable,
    everything()
  ) %>% 
  spread(sex, n) %>% 
  rename(
    Boys = male,
    Girls = female
  ) %>% 
  mutate_at(
    vars(Boys, Girls),
    as.character
  )

descriptives <-
  descriptives %>% 
  bind_rows(race_ethn_descriptives) %>% 
  select(
    variable,
    Boys, 
    Girls
  )

descriptives %>% knitr::kable()
```

# sex differences
```{r}
sex_t_test <- function(x) {
  t.test(x ~ demo$sex)
}

sex_t_test(demo$sumsev_type_THRT)
sex_t_test(demo$income_needs)
sex_t_test(demo$T1_Age)
sex_t_test(demo$T2_Age)
sex_t_test(demo$tanner_av)
sex_t_test(demo$interval)
sex_t_test(demo$tanner_av_t2s1)
```

```{r}
chisq.test(demo$White, demo$sex)
```







# frequencies and chi-squares

## number "low-income"
```{r}
demo %>% 
  count(income_needs < 1) %>% 
  mutate(
    percent = n / sum(n)
  )
```

## number male
```{r}
demo %>% 
  count(sex)
```

##number each race 
```{r}
demo <- 
  demo %>% 
  mutate(
    Race = as.character(race_pr),
    Race = dplyr::recode(
      Race,
      "1" = "Caucasian",
      "2" = "African American",
      "3" = "Hispanic",
      "4" = "Asian",
      "5" = "Biracial",
      "6" = "Other"
    )
  )

demo %>% 
  group_by(sex, Race) %>% 
  summarise(
    n = n()
  ) %>% 
  mutate(
    percent = n / sum(n)
  ) %>% 
  arrange(sex, desc(percent))


demo <-
  demo %>% 
  mutate(
    white = as.factor(
      dplyr::recode(
        Race,
        "Caucasian" = 1,
        .default = 0
      )
    )
  )

chisq.test(demo$white, demo$sex)

```


# Distributions
```{r}
demo %>% 
  mutate(
    income = sjlabelled::as_label(income)
  ) %>% 
  count(income)

demo %>% 
  filter(!is.na(income)) %>% 
  mutate(
    income = sjlabelled::as_label(income)
  ) %>% 
  ggplot(aes(income)) +
  geom_bar(stat = "count") +
  scale_y_continuous(breaks = seq.int(0, 60, 10)) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 12, angle = 300, hjust = -.01),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 16)
  ) +
  labs(
    x = "Family income",
    y = "Count"
  )

ggsave(
  "~/Desktop/ELS/income_TBM/income_TBM_sync/plots/income_bins_hist.png",
  height = 7,
  width = 11
  )

demo %>% 
  ggplot(aes(income_needs)) +
  geom_histogram() +
  #scale_y_continuous(breaks = seq.int(0, 60, 10)) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 16)
  ) +
  labs(
    x = "Income-to-needs ratio",
    y = "Count"
  )

ggsave(
  "~/Desktop/ELS/income_TBM/income_TBM_sync/plots/income_needs_hist.png",
  height = 7,
  width = 11
  )
```

```{r}
demo %>% 
  ggplot(aes(x = T1_Age, fill = sex)) +
  geom_histogram()

demo %>% 
  ggplot(aes(x = T1_Age, fill = sex)) +
  geom_density(alpha = 1/2) +
  scale_fill_manual(
    values = c("red", "blue"),
    labels = c("Girls", "Boys")
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 16),
    legend.text = element_text(size = 14)
  ) +
  labs(
    fill = NULL,
    x = "Age (years) at T1",
    y = "Count"
  )

ggsave(
  "~/Desktop/ELS/income_TBM/income_TBM_sync/plots/age_sex_density.png",
  height = 7,
  width = 11
  )

demo_agematch <-
  demo %>% 
  filter(T1_Age >= 11 & T1_Age <= 12)

demo_agematch %>% 
  count(sex)

demo_agematch %>% 
  count(included_t2)

t.test(demo_agematch$T1_Age ~ demo_agematch$sex)
t.test(demo_agematch$tanner_av ~ demo_agematch$sex)

demo_agematch %>% 
  group_by(sex) %>% 
  summarize_at(
    vars(T1_Age),
    list(~mean, ~sd)
  )

demo_agematch %>% 
  ggplot(aes(x = T1_Age, fill = sex)) +
  geom_density(alpha = 1/2) +
  scale_fill_manual(
    values = c("red", "blue"),
    labels = c("Girls", "Boys")
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 16),
    legend.text = element_text(size = 14)
  ) +
  labs(
    fill = NULL,
    x = "Age (years) at T1",
    y = "Count"
  )

demo_agematch_IDs <-
  demo_agematch %>% 
  select(ELS_ID)

write_csv(demo_agematch_IDs, "~/Desktop/ELS/income_TBM/data/final_data/age_matched_IDs.csv")
```

